---
secretkey: 112345678b0123a5678d012c45678901
accesstokenduration: 1h

httpserver:
  host: localhost
  port: 8081

database:
  host: localhost
  port: 5432
  user: kalite-project
  pass: kalite-project
  name: kalite-project

redis:
  host: localhost
  port: 6379
  pass: kalite-project
  db: 1

elastic: 
  url: http://elasticsearch:9200